defaultBaseImage: gcr.io/distroless/base-debian10
builds:
- main: .
  env:
  - CGO_ENABLED=1
# If you are deploying from M1, you can use this (uncomment below, and
# comment out above), though it does remove the support for the "createca" command.
# But at least you can deploy it from M1 using this.
#  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - "{{ .Env.GIT_HASH }}"
  - -tags
  - "{{ .Env.GIT_VERSION }}"
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
